/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ml.ovcorp;

import ml.ovcorp.music.importer.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

}
