/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ml.ovcorp.music.importer;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) throws Exception {
        ProcessBuilder pb = new ProcessBuilder("python", "yandex-client/main.py");
        Process p = pb.start();
        SpringApplication.run(App.class, args);

    }

}
